name: integration-test
on: [pull_request]
jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    container: seiyab/rust-cc:latest
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: rustup default stable
      - name: test
        run: make test
